// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dcdqenznokjjzgbescyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjZHFlbnpub2tqanpnYmVzY3lpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MTI5OTksImV4cCI6MjA3NDQ4ODk5OX0.acfs6Nr8Sb6FQKZZrK9fgfk3GR1foLYJz4qDLq4R9Gw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});